var DATA = {
    "battles": [
        {
            "id": 1,
            "n": "Match #1",
            "qf": "TO QF1",
            "t1": "fi",
            "a1": "Linda Lampenius and Pete Parkkonen",
            "s1": "Liekinheitin",
            "sc1": "71% ★",
            "t2": "me",
            "a2": "Tamara Živković",
            "s2": "Nova zora",
            "sc2": "29%",
            "w": 1,
            "status": "FINISHED"
        },
        {
            "id": 2,
            "n": "Match #2",
            "qf": "TO QF1",
            "t1": "dk",
            "a1": "Søren Torpegaard Lund",
            "s1": "Før vi går hjem",
            "sc1": "77% ★",
            "t2": "at",
            "a2": "COSMØ",
            "s2": "Tanzschein",
            "sc2": "23%",
            "w": 1,
            "status": "FINISHED"
        },
        {
            "id": 3,
            "n": "Match #3",
            "qf": "TO QF2",
            "t1": "gr",
            "a1": "Akylas",
            "s1": "Ferto",
            "sc1": "56% ★",
            "t2": "al",
            "a2": "Alis",
            "s2": "Nân",
            "sc2": "44%",
            "w": 1,
            "status": "FINISHED"
        },
        {
            "id": 4,
            "n": "Match #4",
            "qf": "TO QF2",
            "t1": "au",
            "a1": "Delta Goodrem",
            "s1": "Eclipse",
            "sc1": "WAIT",
            "t2": "ge",
            "a2": "Bzikebi",
            "s2": "On Replay",
            "sc2": "",
            "w": 0,
            "status": "WAITING"
        },
        {
            "id": 5,
            "n": "Match #5",
            "qf": "TO QF3",
            "t1": "se",
            "a1": "Felicia",
            "s1": "My System",
            "sc1": "WAIT",
            "t2": "am",
            "a2": "Simón",
            "s2": "Paloma rumba",
            "sc2": "",
            "w": 0,
            "status": "WAITING"
        },
        {
            "id": 6,
            "n": "Match #6",
            "qf": "TO QF3",
            "t1": "it",
            "a1": "Sal Da Vinci",
            "s1": "Per sempre sì",
            "sc1": "WAIT",
            "t2": "md",
            "a2": "Satoshi",
            "s2": "Viva, Moldova!",
            "sc2": "",
            "w": 0,
            "status": "WAITING"
        },
        {
            "id": 7,
            "n": "Match #7",
            "qf": "TO QF4",
            "t1": "cy",
            "a1": "Antigoni",
            "s1": "Jalla",
            "sc1": "WAIT",
            "t2": "gb",
            "a2": "Look Mum No Computer",
            "s2": "Eins, Zwei, Drei",
            "sc2": "",
            "w": 0,
            "status": "WAITING"
        },
        {
            "id": 8,
            "n": "Match #8",
            "qf": "TO QF4",
            "t1": "mt",
            "a1": "HVNDS",
            "s1": "Dor",
            "sc1": "WAIT",
            "t2": "bg",
            "a2": "Dara",
            "s2": "Bangaranga",
            "sc2": "",
            "w": 0,
            "status": "WAITING"
        }
    ],
    "qualifiers": [
        { "id": "fi", "a": "L. Lampenius & P. Parkkonen", "s": "Liekinheitin" },
        { "id": "dk", "a": "S. Torpegaard Lund", "s": "Før vi går hjem" },
        { "id": "gr", "a": "Akylas", "s": "Ferto" },
        { "id": "au", "a": "Delta Goodrem", "s": "Eclipse" },
        { "id": "se", "a": "Felicia", "s": "My System" },
        { "id": "it", "a": "Sal Da Vinci", "s": "Per sempre sì" },
        { "id": "cy", "a": "Antigoni", "s": "Jalla" },
        { "id": "mt", "a": "Aidan", "s": "Bella" },
        { "id": "bg", "a": "Dara", "s": "Bangaranga" },
        { "id": "gb", "a": "Look Mum No Computer", "s": "Eins, Zwei, Drei" },
        { "id": "md", "a": "Satoshi", "s": "Viva, Moldova!" },
        { "id": "am", "a": "Simón", "s": "Paloma rumba" },
        { "id": "ge", "a": "Bzikebi", "s": "On Replay" }
    ],
    "eliminated": [
        { "id": "al", "a": "Alis", "s": "Nân" },
        { "id": "me", "a": "Tamara Živković", "s": "Nova zora" },
        { "id": "at", "a": "COSMØ", "s": "Tanzschein" },
        { "id": "lu", "a": "Eva Marija", "s": "Mother Nature" },
        { "id": "ro", "a": "A. Căpitănescu", "s": "Choke Me" },
        { "id": "lt", "a": "Lion Ceccah", "s": "Sólo quiero más" },
        { "id": "hr", "a": "Lelek", "s": "Andromeda" },
        { "id": "lv", "a": "Atvara", "s": "Ēnā" },
        { "id": "cz", "a": "Daniel Zizka", "s": "Crossroads" },
        { "id": "ua", "a": "Lelūka", "s": "Ridnym" },
        { "id": "ee", "a": "Vanilla Ninja", "s": "Too Epic to Be True" },
        { "id": "pt", "a": "Bandidos do Cante", "s": "Rosa" },
        { "id": "az", "a": "Jiva", "s": "Just Go" },
        { "id": "il", "a": "Noam Bettan", "s": "Michelle" },
        { "id": "rs", "a": "Lavina", "s": "Kraj mene" },
        { "id": "fr", "a": "Monroe", "s": "Regarde !" },
        { "id": "pl", "a": "Alicja", "s": "Pray" },
        { "id": "no", "a": "Jonas Lovv", "s": "Ya Ya Ya" },
        { "id": "de", "a": "Sarah Engels", "s": "Fire" },
        { "id": "sm", "a": "Senhit", "s": "Superstar" },
        { "id": "ch", "a": "Veronica Fusaro", "s": "Alice" },
        { "id": "be", "a": "Essyla", "s": "Dancing on the Ice" }
    ]
};
