#!/usr/bin/env python3
import sys
import os

# Путь к Brand Voice для подтягивания контекста
BRAND_VOICE_PATH = "/home/levdanskiy/.gemini/KNOWLEDGE/Brand_Voice_Manifest_Ultimate.md"

def ask_expert_questions(song_name):
    print(f"\n--- 🎤 YOURVISION: ЭКСПЕРТНЫЙ АНАЛИЗ ЗАЯВКИ [{song_name.upper()}] ---")
    print("Ответьте на несколько вопросов для генерации глубокой рецензии:\n")
    
    questions = [
        "1. Музыкальная ДНК: Каков основной жанр и есть ли 'крючок' (hook)?",
        "2. Визуальный потенциал: Что вы видите на сцене во время этой песни?",
        "3. Вердикт автора: Это заявка на победу, на финал или просто качественный филлер?",
        "4. Личный резонанс: Какую эмоцию песня оставляет после первого прослушивания?"
    ]
    
    answers = []
    for q in questions:
        print(q)
        ans = input("> ")
        answers.append(ans)
    
    return answers

def generate_review_draft(song_name, answers):
    # Логика генерации черновика (Bilingual Mirror)
    # Здесь используется упрощенная структура, так как LLM-часть выполняет агент
    draft = f"""
# 🎤 REVIEW: {song_name}
// GENERATED BY EXPERT SYSTEM V1.0 //

RU:
{answers[3]}
В плане музыки это {answers[0]}.
Стейджинг видится как {answers[1]}.
Итог: {answers[2]}

UA:
{answers[3]} (UA Translation)
В музичному плані це {answers[0]}.
Стейджинг бачиться як {answers[1]}.
Підсумок: {answers[2]}
    """
    return draft

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Использование: python3 expert_review_orchestrator.py 'Название песни'")
        sys.exit(1)
    
    song = sys.argv[1]
    # В CLI-среде агента input() может не работать напрямую, 
    # поэтому мы выводим вопросы и ждем, пока пользователь их скопирует или ответит.
    # Но для полной автоматизации я создам шаблон.
    
    print(f"Скрипт готов к работе. Запустите его в интерактивном режиме для сбора данных.")
